### ISSUE TITLE
Kwenta "Switch to L2" button bricked

### ISSUE THREAD

**Issue by JChiaramonte7** [Synthetixio/js-monorepo#62]
This change is causing issues on Kwenta

https://github.com/Synthetixio/js-monorepo/blob/11b3f0c0f941dab2d840c67943c67a86af6b4fdd/packages/optimism-networks/src/constants.ts#L23

![image](https://user-images.githubusercontent.com/4015977/130499341-3325929a-9416-4875-94a5-530ee020182f.png)

Change made in #45

**Comment by fritzschoff** [comment]
There is now a new function that handles switching chains
https://github.com/Synthetixio/js-monorepo/blob/master/packages/providers/src/index.ts#L35
If user does not have optimism added already use `method: 'wallet_addEthereumChain'`
Closing it for now.
