### ISSUE TITLE
Optimistic block explorer permalinks

### ISSUE THREAD

**Issue by JChiaramonte7** [Synthetixio/js-monorepo#63]
Was there a reason for this change? This should have stayed `https://explorer.optimism.io/` because it redirects to optimism's current block explorer.

https://github.com/Synthetixio/js-monorepo/blob/11b3f0c0f941dab2d840c67943c67a86af6b4fdd/packages/optimism-networks/src/constants.ts#L18

Change made in #45

**Comment by fritzschoff** [comment]
seems to be fixed. Closing it for now
